### ISSUE TITLE
Improve 'kw c' output

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#43]
If there is no code style problem in the file, kw shows something like this per file:

```
=========================================================

=========================================================

=========================================================

=========================================================
```

We have to handle it with two approaches:

1. Add a verbose option in the code style, that produces something like this:
```
kw c -v lalala.c
=========================================================
lalala.c: No checkpatch problem
=========================================================
```

2. Show nothing if the file is clean:

```
> kw c xpto.c
>
```

**Comment by rodrigosiqueira** [comment]
Done, see 56534434d5dd551478b4d4066ff3a34eb4b3e932

**Comment by matheustavares** [comment]
This is almost complete, but there are still two points to fix:

1) Running `kw c` on a file (or dir) with \*no\* codestyle problems still prints something:
```
Running checkpatch.pl on: <file or dir>
=========================================================
```

2) Running `kw c` on a dir \*with\* codestyle errors concatenates the output of each file (not printing the separator). Ex:
```
Running checkpatch.pl on: <dir>
=========================================================
dir:file: warning
dir:file: warning
total: 0 errors, 2 warnings, 0 checks, 626 lines checked
dir:file: error
dir:file: warning
total: 1 errors, 1 warnings, 0 checks, 626 lines checked
...
```

@rodrigosiqueira do you want to take a look at this issue?

**Comment by rodrigosiqueira** [comment]
As described in #124, what you are seen is a bug recently introduced; because of this, I added the "bug" label. Additionally, this is an important issue for the alpha version; because of this, I updated the milestone. At this moment, I'm focused on finishing #17. For this reason, I have no bandwidth... if you can take a look at this issue, it could be awesome!
